// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210806.1

#pragma once
#ifndef WINRT_VGLL_2_H
#define WINRT_VGLL_2_H
#include "winrt/impl/VGLL.1.h"
WINRT_EXPORT namespace winrt::VGLL
{
    struct __declspec(empty_bases) SimpleMath : winrt::VGLL::ISimpleMath
    {
        SimpleMath(std::nullptr_t) noexcept {}
        SimpleMath(void* ptr, take_ownership_from_abi_t) noexcept : winrt::VGLL::ISimpleMath(ptr, take_ownership_from_abi) {}
        SimpleMath();
    };
}
#endif
