// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210806.1

#pragma once
#ifndef WINRT_VGLL_1_H
#define WINRT_VGLL_1_H
#include "winrt/impl/VGLL.0.h"
WINRT_EXPORT namespace winrt::VGLL
{
    struct __declspec(empty_bases) ISimpleMath :
        winrt::Windows::Foundation::IInspectable,
        impl::consume_t<ISimpleMath>
    {
        ISimpleMath(std::nullptr_t = nullptr) noexcept {}
        ISimpleMath(void* ptr, take_ownership_from_abi_t) noexcept : winrt::Windows::Foundation::IInspectable(ptr, take_ownership_from_abi) {}
    };
}
#endif
