// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210806.1

#pragma once
#include "winrt/VGLL.h"
namespace winrt::VGLL::implementation
{
    template <typename D, typename... I>
    struct __declspec(empty_bases) SimpleMath_base : implements<D, VGLL::SimpleMath, I...>
    {
        using base_type = SimpleMath_base;
        using class_type = VGLL::SimpleMath;
        using implements_type = typename SimpleMath_base::implements_type;
        using implements_type::implements_type;
        
        hstring GetRuntimeClassName() const
        {
            return L"VGLL.SimpleMath";
        }
    };
}
namespace winrt::VGLL::factory_implementation
{
    template <typename D, typename T, typename... I>
    struct __declspec(empty_bases) SimpleMathT : implements<D, winrt::Windows::Foundation::IActivationFactory, I...>
    {
        using instance_type = VGLL::SimpleMath;

        hstring GetRuntimeClassName() const
        {
            return L"VGLL.SimpleMath";
        }
        auto ActivateInstance() const
        {
            return make<T>();
        }
    };
}

#if defined(WINRT_FORCE_INCLUDE_SIMPLEMATH_XAML_G_H) || __has_include("SimpleMath.xaml.g.h")
#include "SimpleMath.xaml.g.h"
#else

namespace winrt::VGLL::implementation
{
    template <typename D, typename... I>
    using SimpleMathT = SimpleMath_base<D, I...>;
}

#endif
