// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.210806.1

void* winrt_make_VGLL_SimpleMath()
{
    return winrt::detach_abi(winrt::make<winrt::VGLL::factory_implementation::SimpleMath>());
}
WINRT_EXPORT namespace winrt::VGLL
{
    SimpleMath::SimpleMath() :
        SimpleMath(make<VGLL::implementation::SimpleMath>())
    {
    }
}
